CREATE DATABASE IF NOT EXISTS PHONEBOOK;

USE PHONEBOOK

CREATE TABLE IF NOT EXISTS EMPLOYEE
(
	Name VARCHAR(255),
	PhoneNumber VARCHAR(255),
	Email VARCHAR(255),
	ImagePath VARCHAR(255),
	Username VARCHAR(25) NOT NULL UNIQUE,
	Password VARCHAR(255),
	Role VARCHAR (25),
	PRIMARY KEY (Name, PhoneNumber)
)
